Menu
farouqdaif1/Portfolio pull request #13
Opened 2021-10-04 17:21 UTC by farouqdaif1

Add Dynamic menu 
Add linters for js

2021-10-04 18:53 UTC, Davidosky007 requested changes
## Hi @adamteddychang 👋, 

Good job so far! 💪 
* Descriptive commit messages ✔️ 
* No linter errors ✔️ 
* Profesional looking readme file 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-04 18:53 UTC, Davidosky007 commented on index.html
> +              <li><a href="#work">Portoflio</a></li>
* Kindly Fix the desktop nav links as the mobile menu options are visible on desktop
![image](https://user-images.githubusercontent.com/52497246/135907210-bc32e211-9aed-491a-86aa-81b8626977e6.png)

2021-10-04 22:47 UTC, carlos-ssh requested changes
Hi @farouqdaif1 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-04 22:47 UTC, carlos-ssh commented on index.html
> +              <li><a href="#about">About</a></li>
- Follow the requested design guidelines:
![Screen Shot 2021-10-04 at 17 44 18](https://user-images.githubusercontent.com/22258274/135934439-138d4e6b-fbec-4707-bd00-aad2e4894d4b.png)
#
_Yours:_
![Screen Shot 2021-10-04 at 17 45 18](https://user-images.githubusercontent.com/22258274/135934534-856e5fb1-7022-4bd6-a1ed-482e261858db.png)

2021-10-04 22:47 UTC, carlos-ssh commented on index.html
> +
- Provide a License in your README file.

2021-10-05 13:05 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Farouq Daif, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-05 13:07 UTC, merged