Add the work section And about
farouqdaif1/Portfolio pull request #2
Opened 2021-09-17 20:12 UTC by farouqdaif1

- make  a branch
- make works section 
- make about 
thanks for the review ❤️

2021-09-17 21:32 UTC, Leon-Mbegera requested changes
Hi @farouqdaif1 , 

# Required Changes ♻️

Good job so far! You've done a very commendable job 💯 
- Your code is clean and your portfolio looks very professional
- Well done on implementing a style similar to the template provided.

However, there are very few changes that you still need to work on to go to the next project but you are almost there!

## Required changes
- [ ] On your readme file's title, please give a space between the `##` and the text of the title, so that it can acquire the form of a correct bold heading.
- [ ] Check down below for other few inline comments on what to change 👇 

_Check the comments under the review._

## Optional suggestions
N/A

- Once you're done with the changes, please request a re-review with this same pull request. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 21:32 UTC, Leon-Mbegera commented on css/style.css
> +  width: 327px;
- [ ] The class assigned to each of your `see project` buttons gives them a large width that makes them span the entire width of the mobile screen. Please reduce the width size to match the one given in the design template

2021-09-17 21:32 UTC, Leon-Mbegera commented on index.html
> +            <button  class="see" type="button">See Project</button>
- [ ] This element qualifies to be a link since it is a button. Please give it and other similar buttons a hover effective using the `<a>` tag such that whenever a user is scrolling through your portfolio, they can tell it's a clickable element.

2021-09-17 23:59 UTC, farouqdaif1 commented on css/style.css
> +  width: 327px;
I can not understand this I give them the same width in the design template

2021-09-18 00:05 UTC, farouqdaif1 commented on css/style.css
> +  width: 327px;
> * [ ]  The class assigned to each of your `see project` buttons gives them a large width that makes them span the entire width of the mobile screen. Please reduce the width size to match the one given in the design template

text-decoration: none;

2021-09-18 01:21 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @safafa, Good job working on some of the changes requested by the previous reviewer 👏🏼 👏🏼 

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-18 01:21 UTC, safafa commented on index.html
> +              </div>
![image](https://user-images.githubusercontent.com/43698511/133867199-4498271f-4842-42e4-94dd-2903ac34b047.png)

- [ ] Kindly fix the image of each of the cards of the project. I suggest you set the image using the HTML `<img>` tag because the image is related to the content of the webpage and not only used for style purpose.
- [ ]

2021-09-18 03:56 UTC, DanSam5K approved these changes
## Hi @farouqdaif1 ,  ✌️ Approved ✌️ ,  ☺️ 
> Excellent Job so far, you have one well fixing the changes suggested by the previous code reviewer and your project looks amazing keep it up 👍  🕺 
- Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-18 10:55 UTC, merged