Add desktop version
farouqdaif1/Portfolio pull request #4
Opened 2021-09-23 20:38 UTC by farouqdaif1

-- Add desktop version
thanks for the review ❤️

2021-09-23 21:10 UTC, karvel-code requested changes
Hi @farouqdaif1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Git flow has been followed.
- All your checks are passing successfully.

## Required Changes ♻️
_Check the comments under the review._

For this section:
![image](https://user-images.githubusercontent.com/52443674/134583945-6bdb3282-db64-41ad-94e5-ef13fa6848de.png)

- [ ] Have the inside text only contain 2 to 3 lines only.
- [ ] I'd suggest you have only the first project card with the see project button at the bottom. Check the figma design how the rest are designed.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-24 09:30 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️
Hi @farouqdaif1,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **[OPTIONAL]** Please ensure your desktop design looks as similar to the template as possible. The **My Recent Works**, **Multi-Post Stories** and Project cards should align vertically as defined in the template

![farouq](https://user-images.githubusercontent.com/36542986/134651333-ec1bcec4-d854-4123-9a29-a1f33d80cb22.jpg)

- [ ] **[OPTIONAL]** Your ABOUT ME section is missing the background image as defined in the template

![farouq-about-back](https://user-images.githubusercontent.com/36542986/134652074-3cec4cdd-55dd-47e5-a165-4054ca050214.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 09:30 UTC, TedLivist commented on index.html
>                <div class="work-cards">
- [ ] Good job implementing the hover effect as suggested. However, please ensure that the hover effect is as similar to the Figma design as possible

![farouq-hover](https://user-images.githubusercontent.com/36542986/134648608-eee2eb07-ea5f-43c6-9432-d46edec34db5.jpg)

2021-09-24 09:30 UTC, TedLivist commented on index.html
>          <section class="recent-works">
These are requirements but were probably missed as a result of oversight.
- [ ] **[OPTIONAL]** It would be nice if the containers in the mobile version of your app is quite responsive to cover for width sizes more than `375px` **(as it seems that's the max-width defined in your CSS for containers in the mobile version)**

- [ ] **[OPTIONAL]** Looking at the images, it would make more design sense to make the Project cards, and About Me section responsive up to your desktop breakpoint.

![farouq-mobile](https://user-images.githubusercontent.com/36542986/134650157-2f84d1bb-0c42-4535-be22-41c48dee45e1.jpg)

![farouq-mobile-2](https://user-images.githubusercontent.com/36542986/134650180-b18a921a-d1e6-4123-9273-5b5310dd111d.jpg)

2021-09-24 10:09 UTC, carlos-ssh approved these changes
Hi @farouqdaif1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 10:09 UTC, merged